version: '3.8'
services:
    frontend:
        container_name: "shipping-idea-frontend"
        image: "shipping-idea-frontend"
        build:
            context: ./frontend
            dockerfile: Dockerfile
        entrypoint: ["npm", "run", "start"]
        env_file:
            - .env
        ports:
            - 40002:4200
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    backend:
        container_name: "shipping-idea-backend"
        image: "shipping-idea-backend"
        build:
            context: ./backend
            dockerfile: Dockerfile
        entrypoint: ["npm", "run", "start:dev"]
        env_file:
            - .env
        ports:
            - 40000:3000
        networks:
            - shipping-idea-backend
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    postgres:
        container_name: postgres
        image: postgres:15.1-alpine
        networks:
            - shipping-idea-backend
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 40001:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
networks:
    shipping-idea-backend:
volumes:
    postgres-data: